from langchain.agents import create_agent
from langchain.tools import tool , ToolRuntime
from src.schemas.user_schemas import UserContext
from src.utils.model import get_model , getSystemPrompt
# from langchain.agents.middleware import ModelCallLimitMiddleware
from src.access_control.permission_manager import get_allowed_tools

@tool("documentManagmentAgent")
def documentmanagmentAgent(query : str, runtime: ToolRuntime[UserContext]):
    """
        Document Management Agent.

        Acts as the document-management sub-agent of the
        main orchestrator agent.

        Responsibilities:
        - Handle document-related operations requested by the user.
        - Determine which document tools are available for the
        authenticated user's role.
        - Enforce role-based access control before executing
        document operations.
        - Delegate the requested operation to the appropriate
        document-management tool.
        - Return the result of the selected operation.

        Access Control:
        - The user's role is obtained from runtime.context.
        - Only tools permitted for that role are exposed to the
        document-management agent.
        - If no tools are available for the user's role, the
        request is denied.

        Args:
            query:
                Natural-language document-management request
                from the user.

            runtime:
                LangChain runtime containing the authenticated
                user's UserContext, including role, department,
                identity, and email.

        Returns:
            str:
                The final response generated by the document
                management agent, or a permission-denied message.
        
    """

    role = runtime.context.role
    print("\n🔥🔥 DOCUMENT MANAGEMENT AGENT CALLED 🔥🔥")
    print("QUERY:", query)
    print("ROLE:", runtime.context.role)
    print("DEPARTMENT:", runtime.context.department)

    print("🔥 BEFORE get_allowed_tools")

    tools = get_allowed_tools(role)

    print("🔥 AFTER get_allowed_tools")
    print("🔥 TOOLS:", tools)
    print(
        "🔥 TOOL NAMES:",
        [t.name for t in tools],
    )
    print("🔥 AFTER get_allowed_tools")
    print("🔥 TOOLS:", tools)
    print("🔥 TOOL TYPE:", type(tools))
    if not tools:
        return f"Permission denied. No tools are available for role '{role}'."

    model = get_model()

    print("\n🔥 MODEL TYPE:", type(model))
    print("🔥 MODEL:", model)
    documentAgent = create_agent(
        model=model,
        tools=tools,
        context_schema=UserContext,
        system_prompt = f"""
You are the Company Document Management Agent.

AUTHENTICATED USER CONTEXT:

Role: {runtime.context.role}
Department: {runtime.context.department}

The authenticated user's role and department are already verified
by the application. Do not ask the user to confirm their role.

TOOL ROUTING RULES:

1. GET DOCUMENT

If the user asks:
- get a document
- show a document
- retrieve a document
- open a document
- give me information about a document
- get document by source/path

MUST call `get_document`.

Example:

User:
"Get the document /tmp/example.pdf"

Call:

get_document(
    source="/tmp/example.pdf"
)

Pass ONLY the exact document source/path.

2. LIST DOCUMENTS

If the user asks:
- list documents
- show documents
- list all documents
- show all available documents
- list documents in my department
- list Python documents

MUST call `list_documents`.

For example:

User:
"List all available documents in my department"

Call:

list_documents(
    query="List all available documents in my department"
)

IMPORTANT:
The authenticated user's role is "{runtime.context.role}".

If role is "admin" or "manager", list_documents is authorized.

Do NOT say that the user is an employee when the authenticated
role is admin or manager.

Do NOT ask the user to confirm their role.

3. SEARCH DOCUMENTS

If the user asks a question about information inside documents,
call `search_documents`.

4. UPLOAD DOCUMENT

ONLY call `upload_document` when the user explicitly asks to
upload/add/ingest a new document.

5. UPDATE DOCUMENT

ONLY call `update_document` when the user explicitly asks to
update/replace an existing document.

6. DELETE DOCUMENT

ONLY call `delete_document` when the user explicitly asks to
delete/remove an existing document.

GENERAL RULES:

- Always use the appropriate tool.
- Do not answer document operations from general knowledge.
- Do not invent document information.
- Do not ask unnecessary clarification questions.
- Respect the authenticated user's department.
- Never expose another department's documents.
- After a tool call, return the tool's result accurately.
- Do not replace an explicit tool result with a generic fallback.

Return only the final answer.
"""
    )
    print("\n🔥 DOCUMENT AGENT TYPE:", type(documentAgent))
    print("🔥 DOCUMENT AGENT:", documentAgent)

    agent_query = query

    if runtime.context.file_path:
        agent_query += (
            f"\n\nReplacement file path: "
            f"{runtime.context.file_path}"
        )

    result = documentAgent.invoke({"messages": [{"role" :"user", "content":query}]} , context=runtime.context)
    return result["messages"][-1].content