from langchain.agents import create_agent
from langchain.tools import tool , ToolRuntime
from src.schemas.user_schemas import UserContext
from src.utils.model import get_model , getSystemPrompt , getdocsubagent
# from langchain.agents.middleware import ModelCallLimitMiddleware
from src.access_control.permission_manager import get_allowed_tools

@tool("documentManagmentAgent")
def documentmanagmentAgent(query : str, runtime: ToolRuntime[UserContext]):
    """
        Document Management Agent.

        Acts as the document-management sub-agent of the
        main orchestrator agent.

        Responsibilities:
        - Handle document-related operations requested by the user.
        - Determine which document tools are available for the
        authenticated user's role.
        - Enforce role-based access control before executing
        document operations.
        - Delegate the requested operation to the appropriate
        document-management tool.
        - Return the result of the selected operation.

        Access Control:
        - The user's role is obtained from runtime.context.
        - Only tools permitted for that role are exposed to the
        document-management agent.
        - If no tools are available for the user's role, the
        request is denied.

        Args:
            query:
                Natural-language document-management request
                from the user.

            runtime:
                LangChain runtime containing the authenticated
                user's UserContext, including role, department,
                identity, and email.

        Returns:
            str:
                The final response generated by the document
                management agent, or a permission-denied message.
        
    """

    role = runtime.context.role
    print("\n🔥🔥 DOCUMENT MANAGEMENT AGENT CALLED 🔥🔥")
    print("QUERY:", query)
    print("ROLE:", runtime.context.role)
    print("DEPARTMENT:", runtime.context.department)

    print("🔥 BEFORE get_allowed_tools")

    tools = get_allowed_tools(role)

    print("🔥 AFTER get_allowed_tools")
    print("🔥 TOOLS:", tools)
    print(
        "🔥 TOOL NAMES:",
        [t.name for t in tools],
    )
    print("🔥 AFTER get_allowed_tools")
    print("🔥 TOOLS:", tools)
    print("🔥 TOOL TYPE:", type(tools))
    if not tools:
        return f"Permission denied. No tools are available for role '{role}'."

    model = get_model()
    # Get Document Management system prompt from Langfuse
    document_system_prompt = getdocsubagent(
        "ducument_sub_agent"
    )

    print("\n🔥 MODEL TYPE:", type(model))
    print("🔥 MODEL:", model)
    documentAgent = create_agent(
        model=model,
        tools=tools,
        context_schema=UserContext,
        system_prompt=document_system_prompt
    )
    print("\n🔥 DOCUMENT AGENT TYPE:", type(documentAgent))
    print("🔥 DOCUMENT AGENT:", documentAgent)

    agent_query = query

    if runtime.context.file_path:
        agent_query += (
            f"\n\nReplacement file path: "
            f"{runtime.context.file_path}"
        )

    result = documentAgent.invoke({"messages": [{"role" :"user", "content":query}]} , context=runtime.context)
    return result["messages"][-1].content